In [482]:
import pandas as pd
import numpy as np

df = pd.read_csv('forestfires.csv')

headers=['X','Y','month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area']

df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [483]:
df.dtypes

X          int64
Y          int64
month     object
day       object
FFMC     float64
DMC      float64
DC       float64
ISI      float64
temp     float64
RH         int64
wind     float64
rain     float64
area     float64
dtype: object

In [484]:
obj_df=df.select_dtypes(include=['object']).copy()
obj_df.head()

  month  day
0   mar  fri
1   oct  tue
2   oct  sat
3   mar  fri
4   mar  sun

In [485]:
from sklearn.preprocessing import OneHotEncoder

categorial=['month','day']
encoder = OneHotEncoder(drop='first',sparse_output=False)
encoder.fit(df[categorial])
encoded_cols = pd.DataFrame(encoder.transform(df[categorial]), columns=encoder.get_feature_names_out(categorial))
df = pd.concat([df, encoded_cols], axis=1)

df = df.drop(categorial, axis=1)
print(df)

     X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  month_may  \
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...        0.0
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...        0.0
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...        0.0
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...        0.0
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...        0.0
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...  ...        ...
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...        0.0
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...        0.0
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...        0.0
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...        0.0
516  6  3  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...        0.0

     month_nov  month_oct  month_sep  day_mon  day_sat  day_sun  day_thu  \
0          0.0        0.0        0.0      0.0      0.0      0.0      0.0
1          0.0        1.0        0.0      0.0      0.0      0.0      0.0
2          0.0        1.0        0.0      0.0      1.0      0.0      0.0
3          0.0        0.0        0.0      0.0      0.0      0.0      0.0
4          0.0        0.0        0.0      0.0      0.0      1.0      0.0
..         ...        ...        ...      ...      ...      ...      ...
512        0.0        0.0        0.0      0.0      0.0      1.0      0.0
513        0.0        0.0        0.0      0.0      0.0      1.0      0.0
514        0.0        0.0        0.0      0.0      0.0      1.0      0.0
515        0.0        0.0        0.0      0.0      1.0      0.0      0.0
516        1.0        0.0        0.0      0.0      0.0      0.0      0.0

     day_tue  day_wed
0        0.0      0.0
1        1.0      0.0
2        0.0      0.0
3        0.0      0.0
4        0.0      0.0
..       ...      ...
512      0.0      0.0
513      0.0      0.0
514      0.0      0.0
515      0.0      0.0
516      1.0      0.0

[517 rows x 28 columns]

In [486]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 28 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   X          517 non-null    int64
 1   Y          517 non-null    int64
 2   FFMC       517 non-null    float64
 3   DMC        517 non-null    float64
 4   DC         517 non-null    float64
 5   ISI        517 non-null    float64
 6   temp       517 non-null    float64
 7   RH         517 non-null    int64
 8   wind       517 non-null    float64
 9   rain       517 non-null    float64
 10  area       517 non-null    float64
 11  month_aug  517 non-null    float64
 12  month_dec  517 non-null    float64
 13  month_feb  517 non-null    float64
 14  month_jan  517 non-null    float64
 15  month_jul  517 non-null    float64
 16  month_jun  517 non-null    float64
 17  month_mar  517 non-null    float64
 18  month_may  517 non-null    float64
 19  month_nov  517 non-null    float64
 20  month_oct  517 non-null    float64
 21  month_sep  517 non-null    float64
 22  day_mon    517 non-null    float64
 23  day_sat    517 non-null    float64
 24  day_sun    517 non-null    float64
 25  day_thu    517 non-null    float64
 26  day_tue    517 non-null    float64
 27  day_wed    517 non-null    float64
dtypes: float64(25), int64(3)
memory usage: 113.2 KB

In [487]:
df.shape

(517, 28)

In [488]:
df.describe()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,...,0.003868,0.001934,0.029014,0.332689,0.143133,0.162476,0.183752,0.117988,0.123791,0.104449
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,...,0.062137,0.043980,0.168007,0.471632,0.350548,0.369244,0.387657,0.322907,0.329662,0.306138
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [489]:
def outliers(dt,ft):
    med=dt[ft].median()
    Q1, Q3 = dt[ft].quantile(0.25), dt[ft].quantile(0.75)
    IQR = Q3 - Q1

    threshold = 1.5 * IQR
    lower_bound, upper_bound = Q1 - threshold, Q3 + threshold
    ls=dt.index[(df[ft] < lower_bound) | (dt[ft] > upper_bound)]
    return ls

In [490]:
index_list=[]
features_to_scale=['Y','DMC','DC','ISI','temp','RH','wind','rain']
for feature in list(df.columns)[:11]:
    index_list.extend(outliers(df,feature))

In [491]:
def remove(df,ls):
    ls=sorted(set(ls))
    df=df.drop(ls)
    return df

In [492]:
df_clean=remove(df,index_list)

In [493]:
df_clean.shape

(316, 28)

In [494]:
df_clean.describe()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
count,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.0,...,316.0,316.0,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000
mean,4.740506,4.417722,91.815506,110.830063,569.856646,9.132595,19.620886,42.075949,3.729114,0.0,...,0.0,0.0,0.034810,0.376582,0.161392,0.167722,0.186709,0.120253,0.104430,0.107595
std,2.162246,0.906521,1.824519,52.402612,230.973178,2.990914,4.829165,13.368071,1.580810,0.0,...,0.0,0.0,0.183589,0.485297,0.368476,0.374211,0.390296,0.325773,0.306303,0.310360
min,1.000000,3.000000,86.200000,14.600000,25.600000,3.700000,8.200000,15.000000,0.400000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.000000,90.975000,85.025000,501.600000,7.075000,16.600000,32.750000,2.200000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.000000,4.000000,91.800000,108.300000,668.550000,8.500000,19.650000,40.000000,3.600000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6.000000,5.000000,92.825000,137.275000,719.000000,10.600000,22.800000,50.000000,4.900000,0.0,...,0.0,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,6.000000,96.200000,248.400000,822.800000,17.000000,32.600000,82.000000,8.000000,0.0,...,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [495]:
X=df_clean.drop(columns='area')
y=df_clean['area']

In [496]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [497]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
features_to_scale=['X','Y','FFMC','DMC','DC','ISI','temp','RH','wind','rain']

norm_x_train = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns = X_train.columns)
norm_x_test = pd.DataFrame(
    scaler.transform(X_test),
    columns = X_test.columns
)
y_test=np.log1p(y_test)
y_train=np.log1p(y_train)

In [503]:
norm_x_train

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,0.625,0.666667,0.55,0.090676,0.069242,0.308271,0.377049,0.153846,0.592105,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.375,0.000000,0.75,0.370830,0.498996,0.827068,0.733607,0.461538,0.473684,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.000,0.333333,0.40,0.352010,0.750878,0.390977,0.245902,0.584615,0.184211,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.125,0.666667,0.48,0.491446,0.836678,0.248120,0.385246,0.476923,0.355263,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.875,1.000000,0.49,0.378956,0.769192,0.157895,0.622951,0.107692,0.302632,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,0.125,0.333333,0.80,0.460650,0.707852,0.691729,0.295082,0.784615,0.473684,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
248,0.625,0.666667,0.63,0.459367,0.958480,0.488722,0.418033,0.415385,0.236842,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
249,0.625,0.666667,0.47,0.018392,0.006272,0.323308,0.020492,0.553846,0.710526,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
250,0.375,1.000000,0.10,0.039778,0.049047,0.030075,0.237705,0.369231,0.355263,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
251,0.250,0.333333,0.72,0.011548,0.003387,0.466165,0.028689,0.307692,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [498]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(norm_x_train, y_train)

LinearRegression()

In [499]:
from sklearn.metrics import mean_squared_error
predictions = lin_reg.predict(norm_x_test)
rmse =np.sqrt( mean_squared_error(y_test, predictions))
print(rmse)

0.9158536560176651

In [500]:
from sklearn.feature_selection import RFECV


rfe = RFECV(lin_reg, step=1,cv=5,scoring='neg_root_mean_squared_error')
rfe.fit(norm_x_train, y_train)
print(rfe.ranking_)

selected_features = rfe.support_
selected_columns = norm_x_train.columns[selected_features]
print(selected_columns)
best_cr=X_train[selected_columns]

lr_best = LinearRegression()
lr_best.fit(best_cr, y_train)

y_pred = lr_best.predict(norm_x_test[selected_columns])
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse

[11 12 18 14  7 19  4  5  3 24 13 25  1 23 16 17  8 27 26  2 15  9 21 20
  6 10 22]
Index(['month_feb'], dtype='object')

0.7956573193783197

In [501]:
from sklearn.linear_model import Lasso
lasso=Lasso()
lasso.fit(norm_x_train[selected_columns],y_train)
pred_lasso=lasso.predict(norm_x_test[selected_columns])
np.sqrt( mean_squared_error(y_test, pred_lasso))

0.7973828179410216

In [502]:
from sklearn.linear_model import Ridge
ridge=Ridge()
ridge.fit(norm_x_train[selected_columns],y_train)
pred_ridge=ridge.predict(norm_x_test[selected_columns])
np.sqrt(mean_squared_error(y_test,pred_ridge))

0.7965185289543901